### ISSUE TITLE
crypto-js PBKDF2 1,000 times weaker than specified in 1993 and 1.3M times weaker than current standard

### ISSUE THREAD

**Issue by andreyzanovskiy** [Swrve/swrve-web-core-sdk#1]
crypto-js v4.1.1 have a vulnerability 
Please, update crypto-js to v4.2.0

**Comment by KevBrodigan** [comment]
Thanks @andreyzanovskiy we will look at updating this and include in our next release.

**Comment by andreyzanovskiy** [comment]
Thanks a lot! 
Maybe you know when the next version will be released?

**Comment by KevBrodigan** [comment]
@andreyzanovskiy An update has been released for this, thanks.
